version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=${DATABASE_URL} # Make sure to provide your SQL Server URL in a .env file or environment variables
      - JWT_SECRET=${JWT_SECRET}
      - REACT_APP_API_BASE_URL=http://localhost:5000
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
